In [1]:
import pandas as pd
import numpy as np

In [2]:
dataframe = pd.read_csv('DatasetGen.csv', encoding='latin1', sep=';')

In [3]:
dataframe

                 Nome  Sexo  Idade        Cidade  Valor Plano
0       Maria da Silva    F     25      Criciúma          231
1    Leandro Fontanela    M     29     Urussanga          221
2       Gabriel Matias    M     22    Araranguá           125
3       Leonardo Cunha    M     33  Cocal do Sul          150
4  Ana Carolina Souza     F     25       Treviso          200
5      Fernada Ricardo    F     35  Cocal do Sul          335
6      Gustavo Pereira    M     18       Orleans          189
7         Leandro Melo    M     31      Criciúma          184
8          Tiago Cezar    M     25    Araranguá           120
9      Rafael Monteiro    M     29      Criciúma          300

In [4]:
x = dataframe.drop('Valor Plano', axis=1)
x

                 Nome  Sexo  Idade        Cidade
0       Maria da Silva    F     25      Criciúma
1    Leandro Fontanela    M     29     Urussanga
2       Gabriel Matias    M     22    Araranguá
3       Leonardo Cunha    M     33  Cocal do Sul
4  Ana Carolina Souza     F     25       Treviso
5      Fernada Ricardo    F     35  Cocal do Sul
6      Gustavo Pereira    M     18       Orleans
7         Leandro Melo    M     31      Criciúma
8          Tiago Cezar    M     25    Araranguá
9      Rafael Monteiro    M     29      Criciúma

In [5]:
y = dataframe['Valor Plano']
y

0    231
1    221
2    125
3    150
4    200
5    335
6    189
7    184
8    120
9    300
Name: Valor Plano, dtype: int64

In [6]:
# Importando a lib para train_test_split = método houldout
from sklearn.model_selection import train_test_split

# Separando os dados em treino e teste, de acordo com a % passada.
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 1)

In [8]:
# Separando os dados em treino e teste, de acordo com a % passada.
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 1, stratify=x.Sexo)

In [9]:
# Importando o método K-fold
from sklearn.model_selection import KFold

# Criando o modelo, definindo o número de pastas.
modelKFold = KFold(5, random_state=22, shuffle=True)

# Apresentando o número de divisões.
modelKFold.get_n_splits(dataframe)

5

In [10]:
# variável de controle
i = 1
# Percorrendo cada uma das combinações de pastas
for train_index, test_index in modelKFold.split(x):
	# Separando os dados em treino e teste para X e para Y
	x_train, x_test = x.loc[train_index], x.loc[test_index]
	y_train, y_test = y.loc[train_index], y.loc[test_index]
	# Printando as informações.
	print('------------Dados para Treino K-fold {} ---------------'.format(i))
	print('---------- X train ----------')
	print(x_train)
	print('---------- Y train ----------')
	print(y_train)
	print('---------- X test -----------')
	print(x_test)
	print('---------- Y test -----------')
	print(y_test)
	print('-------------------------------------------------------')
	i += 1

------------Dados para Treino K-fold 1 ---------------
---------- X train ----------
                 Nome  Sexo  Idade        Cidade
0       Maria da Silva    F     25      Criciúma
3       Leonardo Cunha    M     33  Cocal do Sul
4  Ana Carolina Souza     F     25       Treviso
5      Fernada Ricardo    F     35  Cocal do Sul
6      Gustavo Pereira    M     18       Orleans
7         Leandro Melo    M     31      Criciúma
8          Tiago Cezar    M     25    Araranguá
9      Rafael Monteiro    M     29      Criciúma
---------- Y train ----------
0    231
3    150
4    200
5    335
6    189
7    184
8    120
9    300
Name: Valor Plano, dtype: int64
---------- X test -----------
               Nome  Sexo  Idade      Cidade
1  Leandro Fontanela    M     29   Urussanga
2     Gabriel Matias    M     22  Araranguá
---------- Y test -----------
1    221
2    125
Name: Valor Plano, dtype: int64
-------------------------------------------------------
------------Dados para Treino K-fold 2 ---------------
---------- X train ----------
                 Nome  Sexo  Idade        Cidade
0       Maria da Silva    F     25      Criciúma
1    Leandro Fontanela    M     29     Urussanga
2       Gabriel Matias    M     22    Araranguá
3       Leonardo Cunha    M     33  Cocal do Sul
4  Ana Carolina Souza     F     25       Treviso
5      Fernada Ricardo    F     35  Cocal do Sul
7         Leandro Melo    M     31      Criciúma
8          Tiago Cezar    M     25    Araranguá
---------- Y train ----------
0    231
1    221
2    125
3    150
4    200
5    335
7    184
8    120
Name: Valor Plano, dtype: int64
---------- X test -----------
             Nome  Sexo  Idade    Cidade
6  Gustavo Pereira    M     18   Orleans
9  Rafael Monteiro    M     29  Criciúma
---------- Y test -----------
6    189
9    300
Name: Valor Plano, dtype: int64
-------------------------------------------------------
------------Dados para Treino K-fold 3 ---------------
---------- X train ----------
                 Nome  Sexo  Idade        Cidade
0       Maria da Silva    F     25      Criciúma
1    Leandro Fontanela    M     29     Urussanga
2       Gabriel Matias    M     22    Araranguá
4  Ana Carolina Souza     F     25       Treviso
5      Fernada Ricardo    F     35  Cocal do Sul
6      Gustavo Pereira    M     18       Orleans
8          Tiago Cezar    M     25    Araranguá
9      Rafael Monteiro    M     29      Criciúma
---------- Y train ----------
0    231
1    221
2    125
4    200
5    335
6    189
8    120
9    300
Name: Valor Plano, dtype: int64
---------- X test -----------
            Nome  Sexo  Idade        Cidade
3  Leonardo Cunha    M     33  Cocal do Sul
7    Leandro Melo    M     31      Criciúma
---------- Y test -----------
3    150
7    184
Name: Valor Plano, dtype: int64
-------------------------------------------------------
------------Dados para Treino K-fold 4 ---------------
---------- X train ----------
                 Nome  Sexo  Idade        Cidade
1    Leandro Fontanela    M     29     Urussanga
2       Gabriel Matias    M     22    Araranguá
3       Leonardo Cunha    M     33  Cocal do Sul
4  Ana Carolina Souza     F     25       Treviso
5      Fernada Ricardo    F     35  Cocal do Sul
6      Gustavo Pereira    M     18       Orleans
7         Leandro Melo    M     31      Criciúma
9      Rafael Monteiro    M     29      Criciúma
---------- Y train ----------
1    221
2    125
3    150
4    200
5    335
6    189
7    184
9    300
Name: Valor Plano, dtype: int64
---------- X test -----------
            Nome  Sexo  Idade      Cidade
0  Maria da Silva    F     25    Criciúma
8     Tiago Cezar    M     25  Araranguá
---------- Y test -----------
0    231
8    120
Name: Valor Plano, dtype: int64
-------------------------------------------------------
------------Dados para Treino K-fold 5 ---------------
---------- X train ----------
               Nome  Sexo  Idade        Cidade
0     Maria da Silva    F     25      Criciúma
1  Leandro Fontanela    M     29     Urussanga
2     Gabriel Matias    M     22    Araranguá
3     Leonardo Cunha    M     33  Cocal do Sul
6    Gustavo Pereira    M     18       Orleans
7       Leandro Melo    M     31      Criciúma
8        Tiago Cezar    M     25    Araranguá
9    Rafael Monteiro    M     29      Criciúma
---------- Y train ----------
0    231
1    221
2    125
3    150
6    189
7    184
8    120
9    300
Name: Valor Plano, dtype: int64
---------- X test -----------
                 Nome  Sexo  Idade        Cidade
4  Ana Carolina Souza     F     25       Treviso
5      Fernada Ricardo    F     35  Cocal do Sul
---------- Y test -----------
4    200
5    335
Name: Valor Plano, dtype: int64
-------------------------------------------------------